import 'package:flutter/material.dart';

import '../../partner/services/partner_proposal_repository.dart';
import '../models/ai_suggestion.dart';
import '../models/enums.dart';
import 'ai_suggestion_repository.dart';
import 'todo_repository.dart';

Future<void> acceptSelfSuggestion({
  required AiSuggestion suggestion,
  required TodoRepository todoRepo,
  required AiSuggestionRepository suggestionRepo,
  String? listId,
}) async {
  if (suggestion.reason == SuggestionReason.stale &&
      suggestion.suggestedDueDate != null) {
    final applied = await todoRepo.applyReminderToOpenTask(
      title: suggestion.title,
      dueDate: suggestion.suggestedDueDate!,
    );
    if (!applied) {
      await todoRepo.createTask(
        title: suggestion.title,
        notes: suggestion.notes,
        priority: TaskPriority.values[suggestion.priority],
        dueDate: suggestion.suggestedDueDate,
        isAllDay: false,
        remindAt: suggestion.suggestedDueDate,
        listId: listId,
      );
    }
  } else {
    await todoRepo.createTask(
      title: suggestion.title,
      notes: suggestion.notes,
      priority: TaskPriority.values[suggestion.priority],
      dueDate: suggestion.suggestedDueDate,
      listId: listId,
    );
  }
  await suggestionRepo.accept(suggestion.id);
}

/// Shows what the partner will see, then sends. Returns false if cancelled
/// or if pairing data is missing.
Future<bool> confirmAndSendSuggestionToPartner({
  required BuildContext context,
  required AiSuggestion suggestion,
  required PartnerProposalRepository proposalRepo,
  required AiSuggestionRepository suggestionRepo,
  required String? myParentId,
}) async {
  if (myParentId == null || myParentId.isEmpty) {
    if (context.mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Koppel eerst WebDAV om een voorstel te sturen.'),
        ),
      );
    }
    return false;
  }

  final confirmed = await showDialog<bool>(
    context: context,
    builder: (ctx) {
      final tt = Theme.of(ctx).textTheme;
      return AlertDialog(
        title: const Text('Dit ziet je partner'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(suggestion.title, style: tt.titleMedium),
            const SizedBox(height: 8),
            Text(
              suggestion.isPartnerTargeted
                  ? 'Bewust algemeen — geen privé-titels of notities.'
                  : 'Titel en eventuele notities van deze suggestie gaan mee.',
              style: tt.bodySmall,
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: const Text('Annuleren'),
          ),
          FilledButton(
            onPressed: () => Navigator.pop(ctx, true),
            child: const Text('Versturen'),
          ),
        ],
      );
    },
  );
  if (confirmed != true) return false;

  await proposalRepo.createManualProposal(
    myParentId: myParentId,
    taskTitle: suggestion.title,
    taskNotes: suggestion.isPartnerTargeted ? null : suggestion.notes,
    taskPriority: TaskPriority.values[suggestion.priority],
    taskDueDate: suggestion.suggestedDueDate,
    autoGenerated: suggestion.isPartnerTargeted,
  );
  await suggestionRepo.accept(suggestion.id);
  if (context.mounted) {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Voorstel naar partner gestuurd')),
    );
  }
  return true;
}
