// Mocks generated by Mockito 5.4.6 from annotations
// in parent/test/sync/sync_orchestrator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i11;

import 'package:drift/drift.dart' as _i2;
import 'package:kinetic_webdav/src/ical/ical_note.dart' as _i9;
import 'package:kinetic_webdav/src/ical/ical_task.dart' as _i8;
import 'package:kinetic_webdav/src/sync/webdav_sync_service.dart' as _i6;
import 'package:kinetic_webdav/src/sync_config.dart' as _i4;
import 'package:kinetic_webdav/src/webdav_client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:parent/db/app_database.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebDavClient_1 extends _i1.SmartFake implements _i3.WebDavClient {
  _FakeWebDavClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncConfig_2 extends _i1.SmartFake implements _i4.SyncConfig {
  _FakeSyncConfig_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i5.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i2.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_0(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i2.MigrationStrategy);
}

/// A class which mocks [WebDavSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebDavSyncService extends _i1.Mock implements _i6.WebDavSyncService {
  MockWebDavSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.WebDavClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeWebDavClient_1(this, Invocation.getter(#client)),
          )
          as _i3.WebDavClient);

  @override
  _i4.SyncConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeSyncConfig_2(this, Invocation.getter(#config)),
          )
          as _i4.SyncConfig);

  @override
  _i7.Future<List<_i8.ICalTask>> pullTasks() =>
      (super.noSuchMethod(
            Invocation.method(#pullTasks, []),
            returnValue: _i7.Future<List<_i8.ICalTask>>.value(<_i8.ICalTask>[]),
          )
          as _i7.Future<List<_i8.ICalTask>>);

  @override
  _i7.Future<void> pushTask(_i8.ICalTask? task) =>
      (super.noSuchMethod(
            Invocation.method(#pushTask, [task]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteTask(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [uid]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i9.ICalNote>> pullNotes() =>
      (super.noSuchMethod(
            Invocation.method(#pullNotes, []),
            returnValue: _i7.Future<List<_i9.ICalNote>>.value(<_i9.ICalNote>[]),
          )
          as _i7.Future<List<_i9.ICalNote>>);

  @override
  _i7.Future<void> pushNote(_i9.ICalNote? note) =>
      (super.noSuchMethod(
            Invocation.method(#pushNote, [note]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteNote(String? uid, {required bool? isShared}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [uid], {#isShared: isShared}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> pullProposals() =>
      (super.noSuchMethod(
            Invocation.method(#pullProposals, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> pushProposal(Map<String, dynamic>? proposalJson) =>
      (super.noSuchMethod(
            Invocation.method(#pushProposal, [proposalJson]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteProposal(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProposal, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> pullLoadMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#pullLoadMetrics, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> pushLoadMetrics(Map<String, dynamic>? metricsJson) =>
      (super.noSuchMethod(
            Invocation.method(#pushLoadMetrics, [metricsJson]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [WebDavClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebDavClient extends _i1.Mock implements _i3.WebDavClient {
  MockWebDavClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  String get username =>
      (super.noSuchMethod(
            Invocation.getter(#username),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#username),
            ),
          )
          as String);

  @override
  String get password =>
      (super.noSuchMethod(
            Invocation.getter(#password),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#password),
            ),
          )
          as String);

  @override
  _i7.Future<List<_i3.WebDavEntry>> propfind(String? collectionPath) =>
      (super.noSuchMethod(
            Invocation.method(#propfind, [collectionPath]),
            returnValue: _i7.Future<List<_i3.WebDavEntry>>.value(
              <_i3.WebDavEntry>[],
            ),
          )
          as _i7.Future<List<_i3.WebDavEntry>>);

  @override
  _i7.Future<_i11.Uint8List> get(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#get, [path]),
            returnValue: _i7.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
          )
          as _i7.Future<_i11.Uint8List>);

  @override
  _i7.Future<void> put(String? path, _i11.Uint8List? bytes, {String? etag}) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path, bytes], {#etag: etag}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> delete(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> mkcol(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#mkcol, [path]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> supportsWebDav() =>
      (super.noSuchMethod(
            Invocation.method(#supportsWebDav, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
