name: kinetic_link

packages:
  - apps/*
  - packages/*

scripts:
  test:
    run: melos exec --dir-exists=test -- flutter test
    description: Run all tests across packages

  analyze:
    run: melos exec -- flutter analyze
    description: Analyze all packages

  pub_get:
    run: melos exec -- flutter pub get
    description: Get pub dependencies for all packages

  build_parent:
    run: flutter build apk --release
    exec:
      scope: parent
    description: Build release APK for parent app

  build_kids:
    run: flutter build apk --release
    exec:
      scope: kids
    description: Build release APK for kids app
