name: kinetic_link

packages:
  - apps/*
  - packages/*

scripts:
  test:
    exec: flutter test
    description: Run all tests across packages
    packageFilters:
      dirExists: test

  analyze:
    exec: flutter analyze
    description: Analyze all packages

  pub_get:
    exec: flutter pub get
    description: Get pub dependencies for all packages

  build_parent:
    exec: flutter build apk --release
    description: Build release APK for parent app
    packageFilters:
      scope: "parent"

  build_kids:
    exec: flutter build apk --release
    description: Build release APK for kids app
    packageFilters:
      scope: "kids"
