name: kinetic_workspace
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - apps/kids
  - apps/parent
  - packages/kinetic_qr_scanner
  - packages/webdav

dev_dependencies:
  melos: ^7.5.1
